import { TFile } from 'obsidian'
import type { App } from 'obsidian'
import type { Preset } from '../types/preset.intf'
import type { QueuedNote } from '../types/news-candidate.intf'
import type { FrontmatterPropertyNames } from '../types/plugin-settings.intf'

/**
 * Regenerate a preset's listing note: one markdown line per published post,
 * ordered by most recent. The file is created (with intermediate folders)
 * if it doesn't exist yet.
 *
 * The listing note is itself in the vault, so without intervention it would
 * appear as a triage candidate on the next run. To prevent that, the
 * configured ignore-flag frontmatter property is set after the body write
 * (which would otherwise wipe any existing frontmatter).
 */
export async function regenerateListingNote(
    app: App,
    preset: Preset,
    notes: QueuedNote[],
    fm: FrontmatterPropertyNames
): Promise<void> {
    const path = preset.listingNotePath.trim()
    if (!path) return

    const lines: string[] = [
        `%% Automatically generated by Ghost Publish (preset: ${preset.name}) %%`,
        '',
        `# ${preset.name} listing`,
        ''
    ]
    for (const n of notes) {
        const date = new Date(n.file.stat.mtime).toISOString().slice(0, 10)
        const linkText = n.file.basename.replace(/]]/g, '')
        lines.push(`- ${date}: [[${linkText}]]`)
    }
    const content = lines.join('\n') + '\n'

    const existing = app.vault.getAbstractFileByPath(path)
    let written: TFile | null = null
    if (existing instanceof TFile) {
        await app.vault.modify(existing, content)
        written = existing
    } else {
        await ensureParentFolder(app, path)
        written = await app.vault.create(path, content)
    }

    if (written) {
        await markAsAutoGenerated(app, written, fm)
    }
}

/**
 * Set the ignore flag on the listing note so subsequent triage runs skip
 * it. Also clears any stale publish-side flags in case the user had
 * previously flagged the file before it became an auto-generated listing.
 */
async function markAsAutoGenerated(
    app: App,
    file: TFile,
    fm: FrontmatterPropertyNames
): Promise<void> {
    await app.fileManager.processFrontMatter(file, (frontmatter: Record<string, unknown>) => {
        frontmatter[fm.ignoreFlag] = true
        delete frontmatter[fm.flag]
        delete frontmatter[fm.preset]
        delete frontmatter[fm.emailFlag]
    })
}

async function ensureParentFolder(app: App, path: string): Promise<void> {
    const slash = path.lastIndexOf('/')
    if (slash <= 0) return
    const parent = path.slice(0, slash)
    if (app.vault.getAbstractFileByPath(parent)) return
    await app.vault.createFolder(parent)
}
