import { TFile } from 'obsidian'
import type { App } from 'obsidian'
import type { Preset } from '../types/preset.intf'
import type { QueuedNote } from '../types/news-candidate.intf'

/**
 * Regenerate a preset's listing note: one markdown line per published post,
 * ordered by most recent. The file is created (with intermediate folders)
 * if it doesn't exist yet.
 */
export async function regenerateListingNote(
    app: App,
    preset: Preset,
    notes: QueuedNote[]
): Promise<void> {
    const path = preset.listingNotePath.trim()
    if (!path) return

    const lines: string[] = [
        `%% Automatically generated by Ghost Publish (preset: ${preset.name}) %%`,
        '',
        `# ${preset.name} listing`,
        ''
    ]
    for (const n of notes) {
        const date = new Date(n.file.stat.mtime).toISOString().slice(0, 10)
        const linkText = n.file.basename.replace(/]]/g, '')
        lines.push(`- ${date}: [[${linkText}]]`)
    }
    const content = lines.join('\n') + '\n'

    const existing = app.vault.getAbstractFileByPath(path)
    if (existing instanceof TFile) {
        await app.vault.modify(existing, content)
        return
    }
    await ensureParentFolder(app, path)
    await app.vault.create(path, content)
}

async function ensureParentFolder(app: App, path: string): Promise<void> {
    const slash = path.lastIndexOf('/')
    if (slash <= 0) return
    const parent = path.slice(0, slash)
    if (app.vault.getAbstractFileByPath(parent)) return
    await app.vault.createFolder(parent)
}
